[package]
name = "peer-piper"
version = "0.1.0"
authors = ["Daniel Olano <danielolanoc@gmail.com>"]
edition = "2018"

[dependencies]
libp2p = "0.16.2"
async-std = { version = "1.5.0", features = ["attributes"] }
futures = "0.3.4"
